### PR TITLE
Run notebook tests on Travis

### PR DESCRIPTION
**Pull request by takluyver**

### CODE REVIEW

**Comment by takluyver** [comment]
I have got the tests passing, but it takes a lot longer to run the notebook tests as well (from 5 minutes to over 20), and some bits are so slow that they occasionally hit Travis' 10-minute timeout without producing any ouput, causing it to fail. @fangohr I'm not sure whether this is what we want - maybe we should use the newly set up Jenkins server to do nbval tests instead.

**Comment by fangohr** [comment]
Great, thank you. 

My initial reaction is to propose to split the notebook validation into a set of notebook that do basic stuff (and are quick) which should be routinely tested on Travis, and some others that take longer to execute, which we can run on a dedicated Jenkins machine. I'd hope that the 'quick' notebooks can include basic documentation of the system, where examples tend to be trivial and not so lengthy to run.

If we want to separate the notebooks into different sets we may need to use the notebook file name to contain particular keywords (such as slow) to exclude them from the fast set of notebooks to validate on Travis. Or at least I cannot think of a way of tagging with with py.test decorators etc.

Is the code coverage affected by running the tests?

**Comment by takluyver** [comment]
I haven't yet tried to integrate these with coverage testing.

**Comment by fangohr** [comment]
I just tried this as you speak. It seems the coverage tool cannot capture the code we execute through the notebook validation:

```
fangohr$ py.test --cov=../../fidimag --cov-report=term --nbval --sanitize-with sanitize_file tutorial-basics.ipynb 
============================= test session starts ==============================
platform darwin -- Python 2.7.11, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /Users/fangohr/git/fidimag, inifile: 
plugins: nbval-0.3.2, cov-2.2.1
collected 18 items 

tutorial-basics.ipynb ..................Coverage.py warning: No data was collected.

--------------- coverage: platform darwin, python 2.7.11-final-0 ---------------
Name                                                                       Stmts   Miss  Cover
----------------------------------------------------------------------------------------------
/Users/fangohr/git/fidimag/fidimag/__init__.py                                16     16     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/__init__.py                      10     10     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/anisotropy.py                    22     22     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/demag.py                         35     35     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/demag_full.py                    19     19     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/demag_hexagonal.py               77     77     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/dmi.py                           52     52     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/eigen.py                        174    174     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/energy.py                        36     36     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/exchange.py                      44     44     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/exchange_new.py                  20     20     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/field.py                         13     13     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/field_test.py                    11     11     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/hexagonal_mesh.py               135    135     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/hexagonal_mesh_test.py           59     59     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/llg.py                          220    220     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/llg_stt_slonczewski_type.py      30     30     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/materials.py                     42     42     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/sim.py                           11     11     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/sllg.py                          25     25     0%
/Users/fangohr/git/fidimag/fidimag/atomistic/zeeman.py                        42     42     0%
/Users/fangohr/git/fidimag/fidimag/common/__init__.py                          5      5     0%
/Users/fangohr/git/fidimag/fidimag/common/batch_task.py                      137    137     0%
/Users/fangohr/git/fidimag/fidimag/common/citation.py                          6      6     0%
/Users/fangohr/git/fidimag/fidimag/common/constant.py                         14     14     0%
/Users/fangohr/git/fidimag/fidimag/common/cuboid_mesh.py                      86     86     0%
/Users/fangohr/git/fidimag/fidimag/common/cuboid_mesh_test.py                 67     67     0%
/Users/fangohr/git/fidimag/fidimag/common/field.py                            13     13     0%
/Users/fangohr/git/fidimag/fidimag/common/fileio.py                           97     97     0%
/Users/fangohr/git/fidimag/fidimag/common/helper.py                          152    152     0%
/Users/fangohr/git/fidimag/fidimag/common/integrators.py                      73     73     0%
/Users/fangohr/git/fidimag/fidimag/common/integrators_test.py                 72     72     0%
/Users/fangohr/git/fidimag/fidimag/common/neb_cartesian.py                   238    238     0%
/Users/fangohr/git/fidimag/fidimag/common/neb_spherical.py                   265    265     0%
/Users/fangohr/git/fidimag/fidimag/common/save_vtk.py                         21     21     0%
/Users/fangohr/git/fidimag/fidimag/common/vtk.py                              30     30     0%
/Users/fangohr/git/fidimag/fidimag/common/vtk_test.py                         31     31     0%
/Users/fangohr/git/fidimag/fidimag/extensions/__init__.py                      0      0   100%
/Users/fangohr/git/fidimag/fidimag/micro/__init__.py                           8      8     0%
/Users/fangohr/git/fidimag/fidimag/micro/anisotropy.py                        21     21     0%
/Users/fangohr/git/fidimag/fidimag/micro/baryakhtar.py                        31     31     0%
/Users/fangohr/git/fidimag/fidimag/micro/demag.py                             73     73     0%
/Users/fangohr/git/fidimag/fidimag/micro/dmi.py                               26     26     0%
/Users/fangohr/git/fidimag/fidimag/micro/energy.py                            29     29     0%
/Users/fangohr/git/fidimag/fidimag/micro/exchange.py                          13     13     0%
/Users/fangohr/git/fidimag/fidimag/micro/llg.py                              236    236     0%
/Users/fangohr/git/fidimag/fidimag/micro/llg_stt.py                           33     33     0%
/Users/fangohr/git/fidimag/fidimag/micro/llg_stt_cpp.py                       30     30     0%
/Users/fangohr/git/fidimag/fidimag/micro/omf.py                               52     52     0%
/Users/fangohr/git/fidimag/fidimag/micro/oommf.py                             98     98     0%
/Users/fangohr/git/fidimag/fidimag/micro/relax.py                             37     37     0%
/Users/fangohr/git/fidimag/fidimag/micro/sim.py                               12     12     0%
/Users/fangohr/git/fidimag/fidimag/micro/simple_demag.py                      32     32     0%
/Users/fangohr/git/fidimag/fidimag/micro/zeeman.py                            48     48     0%
----------------------------------------------------------------------------------------------
TOTAL                                                                       3179   3179     0%

========================== 18 passed in 22.61 seconds ==========================
(p2)bin:ipynb fangohr$ pwd
/Users/fangohr/git/fidimag/doc/ipynb
```

**Comment by takluyver** [comment]
Oh, that's annoying. I was hoping it would just work, but I guess not.

**Comment by fangohr** [comment]
Hm, I thought I'd file an issue with nbval to make this work, but a quick test using the nbval documentation notebooks suggests that something is working. Maybe I just used it incorrectly above (in particular are we measuring the coverage of the files that we are executing?), or it may be easy to fix. Here is the data for reference:
```
(p2)bin:nbval-fangohr fangohr$ pwd
/Users/fangohr/git/nbval-fangohr
(p2)bin:nbval-fangohr fangohr$ ls 
CONTRIBUTORS		README.md		nbval			utils
INSTALL			doc_sanitize		setup.py
LICENSE			documentation.ipynb	tests
(p2)bin:nbval-fangohr fangohr$ py.test tests/ --cov=. --cov-report=term --nbval --sanitize-with tests/sanitize_defaults.cfg
============================================== test session starts ==============================================
platform darwin -- Python 2.7.11, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /Users/fangohr/git/nbval-fangohr, inifile: 
plugins: nbval-0.3.2, cov-2.2.1
collected 9 items 

tests/minimal_example.ipynb ..
tests/sample_notebook.ipynb ......
tests/test_plugin.py .
------------------------------- coverage: platform darwin, python 2.7.11-final-0 --------------------------------
Name                   Stmts   Miss  Cover
------------------------------------------
nbval/__init__.py          1      1     0%
nbval/plugin.py          186     80    57%
setup.py                   2      2     0%
tests/test_plugin.py       8      0   100%
------------------------------------------
TOTAL                    197     83    58%

====== 9 passed in 3.32 seconds ======================
```

**Comment by takluyver** [comment]
I wonder if the tests found fidimag elsewhere when you ran that - had you done `pip install .`? If so, it was probably running with the installed copy rather than the source copy. I think `--cov=` can take a module name (i.e. just `fidimag`) rather than a path - maybe that will work.

**Comment by fangohr** [comment]
Exactly my thinking - but using the module name or explicit path to location of installed package didn’t fix it. I guess next we should try to use coverage.py directly (i.e. not through py.test) and see wether that can be made to work.

**Pull request merged**
