### PR TITLE
DOC-071: Talk about Virtual Micromagnetics

### PR DESCRIPTION
**Pull request by mvousden**
These changes just add Virtual Micromagnetics in the documentation and the README.

Thoughts on modifying http://fidimag.readthedocs.io/en/latest/ipynb/tutorial-docker-container.html to include Virtual Micromagnetics too?

### CODE REVIEW

**Comment by davidcortesortuno** [comment]
Would it be ok just to add an extra section? Like `Run fidimag inside a Docker Container`, but for Virtual Micromagnetics. Do you have anything written for this section?

**Comment by mvousden** [comment]
I haven't written anything in the "Run Fidimag inside a Docker Container" section, but I've modified the "How to Install" section, where we were talking about virtual machines before.

**Comment by davidcortesortuno** [comment]
Mm I was thinking in something outside `Run fidimag inside a Docker Container`, as an extra section :) so you can explain how this would work, add links, some images, etc

**Comment by mvousden** [comment]
Perhaps I should link to the appropriate Virtual Micromagnetics documentation (http://virtual-micromagnetics.readthedocs.io/en/release/container-software.html), as opposed to repeating it.

**Comment by davidcortesortuno** [comment]
Then we should change the `Run fidimag inside a Docker Container` name to something more generic and put Docker as a subsection :O

**Comment by fangohr** [comment]
Hi all, the last finmag  friday (or two weeks before), Thomas and I put together a docker image for Fidimag, and I documented this - currently at http://fidimag.readthedocs.io/en/latest/ipynb/tutorial-docker-container.html

We should make use of that documentation, or at least point to it. It could also move into a better place; I just dumped it somewhere quickly. @davidcortesortuno - can you think about a good place and move it there if necessary?

@mvousden in this context: I think being able to mount the current directory into the docker container is essential for people to use it -- I was gonna add this as an issue in virtualmicromagnetics but as we discuss it here and the Docker image that Thomas and I created provides this, I thought I'll mention it here.

What is not clear to me is how we best deal with the duplication (The duplication comes from virtualmicromagnetics providing a fidimag container amongst many other things): 

Thomas and I created fidimag/notebook which provides the notebook and fidimag and scipy and matplotlib (and pandas I think) and basically all one might need. We have also created fidimag/minimal-py2 and fidimag/minimal-py3 more targeted at running simulations rather than exploring data interactively. The advantage of these images for fidimag over the ones from virtual micromagnetics is that the source to build the image is part of the fidimag repository and relatively straight forward; and thus easier to extend for fidimag users.

**Comment by mvousden** [comment]
In response to @fangohr, this should be done at runtime (https://docs.docker.com/engine/tutorials/dockervolumes/). For clarity, we can run a command like `docker run -v /tmp:/root myImage` (http://stackoverflow.com/questions/15693153/mounting-directory-from-parent-system-to-container-in-docker) to achieve your intended effect. I can add this to the documentation if you like.

**Comment by davidcortesortuno** [comment]
Apparently, @rlc2v07 was updating some of the Installation related documentation. Has this been merged or are there any plans to merge the dev branch?

**Comment by fangohr** [comment]
@mvousden regarding `docker run -v /tmp:/root myImage`, you are right that this happens at run time, and I agree that it should be documented: this is important for users, and they may not be familiar with docker to just know this. And we don't want to force them to work through the docker documentation to find this out.

In addition, we may need to support this from inside the container: it would be really useful if the working directory in the container is the one that is mounted from the host system. This way, you can run a fidimag script x.py that you have in the file system of the host in the current directory, inside the container, and when the script produced output files, these show up in the file system of the host. I think this is really rather key in using the containers. (Otherwise people need to get scripts somehow into the container and then on completion of the run the data files need to come out somehow, before the container shuts down and forgets the file system modifications.) This preparation has to happen when the container is created. [I think Thomas and I got to a working model for this with the fidimag/notebook image.]

**Comment by davidcortesortuno** [comment]
Might I close this PR or should we still update the documentation?

**Comment by fangohr** [comment]
I think the use of fidimag with container is nicely explained at http://fidimag.readthedocs.io/en/latest/ipynb/tutorial-docker-container.html

We should review the installation instructions (http://fidimag.readthedocs.io/en/latest/install.html) and say at the beginning, that there is an alternative way of installing fidimag using a container, which is probably easier, and then point to the container tutorial?

**Comment by davidcortesortuno** [comment]
Ok, then the tutorial must  be updated since the Docker image mentioned there has not been updated in a year. Since M.-A. pushed a Docker file for Travis testing, which generates a Docker container with the latest Fidimag, we should use that :)

**Comment by fangohr** [comment]
I would further make it so that users can build a the image locally, i.e. we should explain what command to run in which folder to create the docker image. This assumes that the user clones the repository, and can then create the container with the most recent Dockerfile. 

Of course this can and should re-use the Dockerfile that builds the container used for the CI tests.

**Pull request closed without merging**
