### PR TITLE
reconnect StepIntegrator and ScipyIntegrator to driver

### PR DESCRIPTION
**Pull request by logicabrity**

### CODE REVIEW

**Comment by davidcortesortuno** [comment]
Does the `scipy` integrator only includes the `dopri5` method? I think Scipy had some others

**Comment by davidcortesortuno** [comment]
Ah sorry i saw you added the option, everything seems ok then :)

**Comment by logicabrity** [comment]
It's a good default I think :)

Von meinem iPhone gesendet

**Comment by davidcortesortuno** [comment]
We need to change `set_tols` in the scipy integrator test

**Pull request merged**
